{
 "title": "perfoTron-dashboard",
 "description": "Monitor your Load Test Live using this dashboard. Load Ingestion Tool : Jmeter, Data Source:Influx",
 "tags": [
  "load_test",
  "sample-dashboard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   {
    "name": "application",
    "query": "SHOW TAG VALUES WITH KEY = \"application\""
   },
   {
    "name": "transaction",
    "label": "Transaction",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$application$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all'"
   },
   { "name": "measurement_name", "label": "Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   {
    "name": "aggregation",
    "label": "Aggregation Interval",
    "query": "1s,10s,30s,60s,600s,1800s,3600s"
   },
   {
    "name": "build_number",
    "query": "SHOW TAG VALUES FROM \"events\" WITH KEY = \"tags\""
   },
   {
    "name": "server",
    "label": "server",
    "query": "SHOW TAG VALUES FROM \"server_stats\" WITH KEY = \"server\""
   }
  ]
 },
 "panels": [
  {
   "title": "India Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error  Indicator",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (sum(\"countError\")/sum(\"count\") * 100 )  FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time(ms)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"avg\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Indicator",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"avg\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunnyvale Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate %",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (sum(\"count\") - sum(\"countError\")) / (sum(\"count\")) FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE ((\"application\" =~ /^$application$/) AND (\"transaction\" = 'all' ) AND (statut = 'all') ) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Error Rate %",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT ( sum(\"countError\")/sum(\"count\")) FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Throughput - req/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Req / sec",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT ((sum(\"count\"))/(count(\"count\")*5)) FROM \"jmeter\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Threads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"maxAT\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (average)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT \"avg\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Stats (Min, Max, Average, 90th Percentile, Received Bytes)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") as \"Total Calls\", last(\"min\") AS \"Min(ms)\", last(\"max\") AS \"Max(ms)\", last(\"avg\") AS \"Avg(ms)\", last(\"pct90.0\") AS \"pct_90(ms)\", sum(\"rb\") as Received_Byte FROM \"jmeter\" WHERE (\"statut\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic Sent Byte",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction sent bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"sb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Traffic Received Byte",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction received bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"rb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors per Transaction",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 6 },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" =~ /.*/) AND $timeFilter GROUP BY \"responseCode\",\"responseMessage\",\"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" }
        ],
        [
         { "params": [ "responseMessage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Individual Transaction Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests - $transaction",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^$transaction$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Failed Requests - $transaction",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Rate % - $transaction",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT    (sum(\"error\")/sum(\"all\")) as \"error percentage\" FROM (SELECT \"count\" as \"all\" FROM \"jmeter\" WHERE \"transaction\" =~ /^$transaction$/ AND \"statut\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter), (SELECT \"count\" as \"error\" FROM \"jmeter\" WHERE \"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/ AND $timeFilter)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" =~ /.*/ AND \"transaction\" =~ /^$transaction$/ ) AND $timeFilter GROUP BY \"transaction\",\"responseCode\",\"responseMessage\",\"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" }
        ],
        [
         { "params": [ "responseMessage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput - $transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Req / s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"count\") / $send_interval FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "5s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE \"application\" =~ /^$application$/ AND \"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times - $transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"avg\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "90th Percentile",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct90.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$transaction$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Perfotron Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "DISK USAGE %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "server_stats",
       "query": "SELECT (\"counter_value\") FROM \"server_stats\" WHERE (\"counter_name\" = 'disk_usage' ) AND $timeFilter GROUP BY \"server\"",
       "select": [
        [
         { "params": [ "actual" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "counter_name", "operator": "=", "value": "disk_usage" }
       ]
      }
     ]
    },
    {
     "title": "CPU  USED%",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "server_stats",
       "query": "SELECT (\"counter_value\") FROM \"server_stats\" WHERE (\"counter_name\" = 'cpu') AND $timeFilter GROUP BY \"server\"",
       "select": [
        [
         { "params": [ "actual" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "counter_name", "operator": "=", "value": "cpu" },
        { "condition": "AND", "key": "env", "operator": "=", "value": "stg" }
       ]
      }
     ]
    },
    {
     "title": "USED_MEMORY(MB)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "server_stats",
       "query": "SELECT (\"counter_value\") FROM \"server_stats\" WHERE (\"counter_name\" = 'used_memory_mb') AND $timeFilter GROUP BY \"server\"",
       "select": [
        [
         { "params": [ "actual" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "counter_name", "operator": "=", "value": "used_memory_mb" }
       ]
      }
     ]
    },
    {
     "title": "AVAILABLE_MEMORY(MB)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "server_stats",
       "query": "SELECT (\"counter_value\") FROM \"server_stats\" WHERE (\"counter_name\" = 'available_memory_mb') AND $timeFilter GROUP BY \"server\"",
       "select": [
        [
         { "params": [ "actual" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "counter_name", "operator": "=", "value": "available_memory_mb" },
        { "condition": "AND", "key": "env", "operator": "=", "value": "stg" }
       ]
      }
     ]
    }
   ]
  }
 ]
}